.PHONY: all clean

all:
clean :

install: all
	install  -m 0644 css/*  $(DESTDIR)/var/www/css
	install  -m 0644 images/*  $(DESTDIR)/var/www/images
	install  -m 0644 js/*  $(DESTDIR)/var/www/js
	install  -m 0644 index.html  $(DESTDIR)/var/www/


